{
 "title": "Photo Frames",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "⏱️ Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"photoframe-home\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD Card used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(node_filesystem_size_bytes{instance=\"photoframe-home\", fstype!~\"tmpfs|overlay|squashfs\"})\r\n- sum(node_filesystem_avail_bytes{instance=\"photoframe-home\", fstype!~\"tmpfs|overlay|squashfs\"})\r\n)\r\n/\r\nsum(node_filesystem_size_bytes{instance=\"photoframe-home\", fstype!~\"tmpfs|overlay|squashfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏱️ Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"photoframe-batanovs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD Card used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(node_filesystem_size_bytes{instance=\"photoframe-batanovs\", fstype!~\"tmpfs|overlay|squashfs\"})\r\n- sum(node_filesystem_avail_bytes{instance=\"photoframe-batanovs\", fstype!~\"tmpfs|overlay|squashfs\"})\r\n)\r\n/\r\nsum(node_filesystem_size_bytes{instance=\"photoframe-batanovs\", fstype!~\"tmpfs|overlay|squashfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏱️ Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"photoframe-cherednychoks\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD Card used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(node_filesystem_size_bytes{instance=\"photoframe-cherednychoks\", fstype!~\"tmpfs|overlay|squashfs\"})\r\n- sum(node_filesystem_avail_bytes{instance=\"photoframe-cherednychoks\", fstype!~\"tmpfs|overlay|squashfs\"})\r\n)\r\n/\r\nsum(node_filesystem_size_bytes{instance=\"photoframe-cherednychoks\", fstype!~\"tmpfs|overlay|squashfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{instance=\"photoframe-home\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{instance=\"photoframe-home\", mode=\"idle\"}[5m])))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"photoframe-home\"} / node_memory_MemTotal_bytes{instance=\"photoframe-home\"}))",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes{instance=\"photoframe-home\"} / clamp_min(node_memory_SwapTotal_bytes{instance=\"photoframe-home\"},1)))",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "CPU Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{instance=\"photoframe-batanovs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{instance=\"photoframe-batanovs\", mode=\"idle\"}[5m])))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"photoframe-batanovs\"} / node_memory_MemTotal_bytes{instance=\"photoframe-batanovs\"}))",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes{instance=\"photoframe-batanovs\"} / clamp_min(node_memory_SwapTotal_bytes{instance=\"photoframe-batanovs\"},1)))",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "CPU Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{instance=\"photoframe-cherednychoks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{instance=\"photoframe-cherednychoks\", mode=\"idle\"}[5m])))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"photoframe-cherednychoks\"} / node_memory_MemTotal_bytes{instance=\"photoframe-cherednychoks\"}))",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes{instance=\"photoframe-cherednychoks\"} / clamp_min(node_memory_SwapTotal_bytes{instance=\"photoframe-cherednychoks\"},1)))",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Synced (36h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({instance=\"photoframe-home\"} |= \"Sync complete\" [36h]))"
    }
   ]
  },
  {
   "title": "Errors (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({instance=\"photoframe-home\"} |~ \"(?i)(error|failed|exception)\" [1d])"
    }
   ]
  },
  {
   "title": "Synced (36h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({instance=\"photoframe-batanovs\"} |= \"Sync complete\" [36h]))"
    }
   ]
  },
  {
   "title": "Errors (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({instance=\"photoframe-batanovs\"} |~ \"(?i)(error|failed|exception)\" [1d])"
    }
   ]
  },
  {
   "title": "Synced (36h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({instance=\"photoframe-cherednychoks\"} |= \"Sync complete\" [36h]))"
    }
   ]
  },
  {
   "title": "Errors (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({instance=\"photoframe-cherednychoks\"} |~ \"(?i)(error|failed|exception)\" [1d])"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"photoframe-home\"} |~ \"(?i)(error|failed|exception)\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"photoframe-batanovs\"} |~ \"(?i)(error|failed|exception)\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"photoframe-cherednychoks\"} |~ \"(?i)(error|failed|exception)\""
    }
   ]
  },
  {
   "title": "PhotoFrame Home",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"photoframe-home\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PhotoFrame Batanovs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"photoframe-batanovs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PhotoFrame Cherednychoks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"photoframe-cherednychoks\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last sync",
   "type": "logs",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"photoframe-home\"} |= \"Sync complete\""
    }
   ]
  },
  {
   "title": "Last sync",
   "type": "logs",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"photoframe-batanovs\"} |= \"Sync complete\""
    }
   ]
  },
  {
   "title": "Last sync",
   "type": "logs",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"photoframe-cherednychoks\"} |= \"Sync complete\""
    }
   ]
  }
 ]
}